### ISSUE TITLE
Qualification Reports

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/RE-Test-Reports#16]
Now that we were able to run [Qualification-CKD](https://github.com/Open-Systems-Pharmacology/RE-Test-Reports/blob/main/tests/Reports/Qualification-CKD/Report.md) , we can add more qualification reports in our tests.

> [!NOTE]
> The Qualification-CKD workflow took 6 min &#128515; 
> The qualification runner is not taken into account in this time count

@Yuri05 
- Could you provide a list of the next qualification reports to include ?
- I added "Draft" as watermark, since these are tests, let me know if we should change it

**Comment by msevestre** [comment]
Does it also run the PKSim part ?  Freaking awesome

Github action minutes donation welcome;)

**Comment by Yuri05** [comment]
> Freaking awesome

Fully agree.

@pchelle I have added some evaluation/qualification plans to the list.

**Comment by pchelle** [comment]
> Does it also run the PKSim part ? 

I think so, I installed both qualification runner and PKSim portable, then I run the initial Input through them with the function [`startQualificationRunner()`](https://github.com/Open-Systems-Pharmacology/RE-Test-Reports/blob/26b51e870d764361bb8b54f6ae9d4c622b0997d2/R/report-qualification-ckd.R#L54C1-L63)

In the [Github Action log](https://github.com/Open-Systems-Pharmacology/RE-Test-Reports/actions/runs/9680928836/job/26710279524#step:7:77), I get this information about the qualification runner:

```
info: QualificationRunner[0]
      Starting qualification workflow
info: QualificationRunner[0]
      Starting validation runs...
info: QualificationRunner[0]
      Starting qualification runs...
info: QualificationRunner[0]
      Qualification scenario finished in 01m:33s:449ms
info: QualificationRunner[0]
      Qualification Workflow finished
```
