### ISSUE TITLE
Qualification DDI

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/RE-Test-Reports#38]
@Yuri05 
The test reports currently do not cover for DDI Qualification Reports that usually include DDI figures and Comparison Time Profiles.
Would there be one of our qualification DDI repo that I could use as test ?

**Comment by Yuri05** [comment]
As long as our OSP DDI quali reports are not migrated: take this one
https://github.com/Yuri05/TestReport/tree/main/TestInput_01_DDI
